import mongoose from 'mongoose';

const OrderSchema = new mongoose.Schema(
  {
    customer_id: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
    driver_id: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
    status: { type: String, index: true },
    service_type: String,
    schedule_type: { type: String, default: 'now' },
    scheduled_time: Date,
    tracking_code: { type: String, index: true },
    pickup_address: String,
    pickup_lat: Number,
    pickup_lng: Number,
    dropoff_address: String,
    dropoff_lat: Number,
    dropoff_lng: Number,
    pickup_contact_name: String,
    pickup_contact_phone: String,
    dropoff_contact_name: String,
    dropoff_contact_phone: String,
    package_type: String,
    package_size: String,
    package_weight: Number,
    notes: String,
    insurance: { type: Boolean, default: false },
    promo_code: String,
    pricing_json: mongoose.Schema.Types.Mixed,
    vat: Number,
    total: Number,
    payment_method: { type: String, default: 'cash' },
    cod_amount: { type: Number, default: 0 },
    eta_minutes: Number,
    eta_text: String,
    sla_status: { type: String, default: 'on_track' },
    proof_method: { type: String, default: 'otp' },
    proof_otp: String,
    proof_confirmed_at: Date,
    cancellation_reason: String,
    cancellation_fee: { type: Number, default: 0 },
    refund_amount: { type: Number, default: 0 },
    failure_reason: String,
    return_reason: String,
    created_at: { type: Date, default: Date.now },
    updated_at: { type: Date, default: Date.now },
  },
  { collection: 'orders' }
);

export default mongoose.models.Order || mongoose.model('Order', OrderSchema);
